In [1]:
#https://www.youtube.com/watch?v=j-3vuBynnOE&list=PLvbc8GGAy87LYN-2UWTJKDms1NlJYrYBL&index=3
import numpy as np
import matplotlib.pyplot as plt
import os #for file path
#import cv2 #for image operations
from PIL import Image


In [2]:
DATADIR="input-test/images"
CATEGORIES = ["apple_pie","chicken_curry","churros","macarons","tiramisu"]


In [3]:
for category in CATEGORIES:
    path = os.path.join(DATADIR, category) #input-test/imaages/apple_pie
    for img in os.listdir(path): #going through each image in the category folder
       # imag_array = cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE)

        path2 = path + '/' + img

        img = Image.open(path2)
        

        #plt.imshow(imag_array,cmap= 'gray')
        # Opens a image in RGB mode  
        im = img

        # Size of the image in pixels (size of orginal image)  
        # (This is not mandatory)  
        width, height = im.size  

        # Setting the points for cropped image  
        left = 4
        top = height / 5
        right = 154
        bottom = 3 * height / 5

        # Cropped image of above dimension  
        # (It will not change orginal image)  
        #im1 = im.crop((left, top, right, bottom)) 
        newsize = (64, 64) 
        im1 = im.resize(newsize) 

        imag_array = np.array(im1)
        print(img)
        print(imag_array.shape)
        
        break
    break

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=384x512 at 0x234BBA7C198>
(64, 64, 3)


In [4]:
print(imag_array)

[[[ 75  64  41]
  [ 89  79  57]
  [ 93  85  62]
  ...
  [152 158 136]
  [158 165 150]
  [142 150 135]]

 [[118 105  71]
  [111  97  62]
  [112  94  62]
  ...
  [119  98  66]
  [131 118  90]
  [147 143 115]]

 [[127 107  65]
  [129 109  65]
  [128 102  60]
  ...
  [114  92  59]
  [115  92  60]
  [117  96  64]]

 ...

 [[146 109  51]
  [152 119  60]
  [160 125  69]
  ...
  [113 110  92]
  [133 135 123]
  [139 141 133]]

 [[132  95  38]
  [137 103  50]
  [150 118  67]
  ...
  [ 87  76  51]
  [ 92  81  62]
  [104  99  84]]

 [[102  68  22]
  [111  78  27]
  [122  90  37]
  ...
  [ 90  79  62]
  [ 80  64  44]
  [ 78  63  38]]]


In [5]:
training_data=[]

def create_training_data():
    for category in CATEGORIES:
        path = os.path.join(DATADIR, category) #input-test/images/apple_pie
        class_num=CATEGORIES.index(category)     
        
        for img in os.listdir(path): #going through each image in the category folder
            try:
                #path = path + '/' + img     
                
                #imag_array = cv2.imread(os.path.join(path,img),cv2.IMREAD_GRAYSCALE)
                
                path = path + '/' + img

                img = Image.open(path2)
                
                #plt.imshow(imag_array,cmap= 'gray')
                # Opens a image in RGB mode  
                im = img

                # Size of the image in pixels (size of orginal image)  
                # (This is not mandatory)  
                width, height = im.size  

                # Setting the points for cropped image  
                left = 4
                top = height / 5
                right = 154
                bottom = 3 * height / 5

                # Cropped image of above dimension  
                # (It will not change orginal image)  
                im1 = im.crop((left, top, right, bottom)) 
                newsize = (64, 64) 
                im1 = im1.resize(newsize) 

                imag_array = np.array(im1)

                training_data.append([imag_array,class_num])
            except Exception as e:
                pass
        
create_training_data()

In [8]:
training_data[3][0].shape

(64, 64, 3)

In [ ]:
im.show() 

In [ ]:
print(len(training_data))

In [ ]:
#shuffle the data so it doesn't only learn one thing at a time and swtich minds
import random

random.shuffle(training_data)

In [ ]:
#1st image 64x64 array, 
training_data[0]

In [ ]:
X = []
y = []

In [ ]:
for features, label in training_data:
    X.append(features)
    y.append(label)

#1 is for the grey scale, if change to 3 will be for color images
X = np.array(X).reshape(-1,IMG_SIZE,IMG_SIZE,3)

In [ ]:
import pickle

In [ ]:
#save your transformed data
pickle_out = open("X.pickle","wb")
pickle.dump(X,pickle_out)
pickle_out.close()

In [ ]:
pickle_out = open("y.pickle","wb")
pickle.dump(y,pickle_out)
pickle_out.close()